services:
  db:
    image: postgres:15
    container_name: auditax-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auditmaster
    ports:
      - "5432:5432"
